version: "3.7"

services:
  web:
    image: 179275389692.dkr.ecr.us-east-1.amazonaws.com/aironnet-web:1.0.0
    command: gunicorn website.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    env_file:
      - .env.prod
    depends_on:
      - db

  db:
    image: postgres:12.0-alpine
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env.prod.database

  admin:
    image: 179275389692.dkr.ecr.us-east-1.amazonaws.com/aironnet-admin:1.0.0
    container_name: admin
    env_file: 
      - .env.frontend.prod
    depends_on: 
      - web

  nginx-web:
    image: nginx:latest
    volumes:
      - ./conf/templates/default-web.conf.template:/etc/nginx/templates/default.conf.template:ro
      - static_volume:/etc/nginx/data/staticfiles
      - media_volume:/etc/nginx/data/mediafiles
    depends_on:
      - web
      - admin
    ports:
      - 8005:80

  nginx-admin:
    image: nginx:latest
    volumes:
      - ./conf/templates/default-admin.conf.template:/etc/nginx/templates/default.conf.template:ro
      - static_volume:/etc/nginx/data/staticfiles
      - media_volume:/etc/nginx/data/mediafiles
    depends_on:
      - web
      - admin
    ports:
      - 8007:80


volumes:
  static_volume:
  media_volume: